package persistence;

import java.io.*;

 /**
  * Asistente Value Object.
  * This class is value object representing database table acemuceva
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Asistente implements Cloneable, Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int cedula;
    private String nombre;
    private int celular;
    private String email;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Asistente () {

    }

    public Asistente (int cedulaIn) {

          this.cedula = cedulaIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getCedula() {
          return this.cedula;
    }
    public void setCedula(int cedulaIn) {
          this.cedula = cedulaIn;
    }

    public String getNombre() {
          return this.nombre;
    }
    public void setNombre(String nombreIn) {
          this.nombre = nombreIn;
    }

    public int getCelular() {
          return this.celular;
    }
    public void setCelular(int celularIn) {
          this.celular = celularIn;
    }

    public String getEmail() {
          return this.email;
    }
    public void setEmail(String emailIn) {
          this.email = emailIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int cedulaIn,
          String nombreIn,
          int celularIn,
          String emailIn) {
          this.cedula = cedulaIn;
          this.nombre = nombreIn;
          this.celular = celularIn;
          this.email = emailIn;
    }


    /** 
     * hasEqualMapping-method will compare two Asistente instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Asistente valueObject) {

          if (valueObject.getCedula() != this.cedula) {
                    return(false);
          }
          if (this.nombre == null) {
                    if (valueObject.getNombre() != null)
                           return(false);
          } else if (!this.nombre.equals(valueObject.getNombre())) {
                    return(false);
          }
          if (valueObject.getCelular() != this.celular) {
                    return(false);
          }
          if (this.email == null) {
                    if (valueObject.getEmail() != null)
                           return(false);
          } else if (!this.email.equals(valueObject.getEmail())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Asistente, mapping to table acemuceva\n");
        out.append("Persistent attributes: \n"); 
        out.append("cedula = " + this.cedula + "\n"); 
        out.append("nombre = " + this.nombre + "\n"); 
        out.append("celular = " + this.celular + "\n"); 
        out.append("email = " + this.email + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Asistente cloned = new Asistente();

        cloned.setCedula(this.cedula); 
        if (this.nombre != null)
             cloned.setNombre(new String(this.nombre)); 
        cloned.setCelular(this.celular); 
        if (this.email != null)
             cloned.setEmail(new String(this.email)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
